// Generated by CoffeeScript 1.4.0
(function() {
  var categories_tree, k, regions_common, regions_tree, v;

  regions_common = ['', 'occasions', 'bonnes_affaires'];

  regions_tree = {
    alsace: ['bas_rhin', 'haut_rhin'],
    aquitaine: [],
    auvergne: [],
    basse_normandie: [],
    bourgogne: [],
    bretagne: [],
    centre: [],
    champagne_ardenne: [],
    corse: [],
    franche_comte: [],
    haute_normandie: ['eure', 'seine_maritime'],
    ile_de_france: ["paris", "seine_et_marne", "yvelines", "essonne", "hauts_de_seine", "seine_saint_denis", "val_de_marne", "val_d_oise"],
    languedoc_rousillon: [],
    limousin: [],
    lorraine: [],
    midi_pyrenees: [],
    nord_pas_de_calais: [],
    pays_de_la_loire: [],
    picardie: [],
    poitou_charentes: [],
    provence_alpes_cote_d_azur: [],
    rhone_alpes: [],
    guadeloupe: [],
    martinique: [],
    guyane: [],
    reunion: []
  };

  categories_tree = {
    _vehicules_: {
      voitures: {},
      motos: {},
      caravaning: {},
      utilitaires: {},
      equipement_auto: {},
      equipement_moto: {},
      equipement_caravaning: {},
      nautisme: {},
      equipement_nautisme: {}
    },
    _immobilier_: {
      ventes_immobilieres: {},
      locations: {
        mrs: {
          type: Number
        },
        mre: {
          type: Number
        },
        ros: {
          type: Number
        },
        roe: {
          type: Number
        },
        sqs: {
          type: 'list',
          values: {
            0: 0,
            1: 20,
            2: 25,
            3: 30,
            4: 35,
            5: 40,
            6: 50,
            7: 60,
            8: 70,
            9: 80,
            10: 90,
            11: 100,
            12: 110,
            13: 120,
            14: 150,
            15: 300
          }
        },
        sqe: {
          type: 'list',
          values: {
            0: 0,
            1: 20,
            2: 25,
            3: 30,
            4: 35,
            5: 40,
            6: 50,
            7: 60,
            8: 70,
            9: 80,
            10: 90,
            11: 100,
            12: 110,
            13: 120,
            14: 150,
            15: 300,
            16: '350+'
          }
        },
        ret: {
          type: 'array',
          values: {
            1: 'maison',
            2: 'appartement',
            3: 'terrain',
            4: 'parking',
            5: 'autre'
          }
        }
      },
      colocations: {},
      locations_de_vacances: {},
      bureaux_commerces: {}
    },
    _multimedia_: {},
    _maison_: {},
    _loisirs_: {},
    _emploi_services_: {},
    _: {
      autres: {}
    }
  };

  module.exports = {
    regions_tree: regions_tree,
    regions: (function() {
      var _results;
      _results = [];
      for (k in regions_tree) {
        v = regions_tree[k];
        _results.push(k);
      }
      return _results;
    })(),
    categories_tree: categories_tree,
    categories: (function() {
      var _results;
      _results = [];
      for (k in categories_tree) {
        v = categories_tree[k];
        _results.push(k);
      }
      return _results;
    })()
  };

}).call(this);
