// Generated by CoffeeScript 1.7.1
(function() {
  var Item, cheerio, clean_string, defs, request,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  cheerio = require('cheerio');

  request = require('request');

  defs = require('./defs');

  clean_string = require('./utils').clean_string;

  Item = (function() {
    function Item(arg) {
      this.arg = arg;
      this.perform = __bind(this.perform, this);
      this.parseHTML = __bind(this.parseHTML, this);
      this.getUrl = __bind(this.getUrl, this);
    }

    Item.prototype.getUrl = function() {
      switch (typeof this.arg) {
        case 'number':
          this.item_id = this.arg;
          break;
        case 'object':
          if (this.arg.href != null) {
            this.url = this.arg.href;
          }
          break;
        case 'string':
          if (parseInt(this.arg).toString() === this.arg) {
            this.item_id = this.arg;
          } else if (/^http/.test(this.arg)) {
            this.url = this.arg;
          } else {
            throw new Error('Item parsing error');
          }
      }
      if (this.item_id) {
        this.url = "http://www.leboncoin.fr/locations/" + this.item_id + ".htm?ca=11_s";
      }
      return this.url;
    };

    Item.prototype.parseHTML = function(html) {
      throw new Error('Not implemented');
    };

    Item.prototype.perform = function(callback) {
      var _url;
      _url = this.getUrl();
      return request(_url, (function(_this) {
        return function(error, response, html) {
          var attrs;
          attrs = _this.parseHTML(html);
          return callback({
            error: error,
            response: response,
            html: html,
            attrs: attrs
          });
        };
      })(this));
    };

    return Item;

  })();

  module.exports = Item;

}).call(this);
