// Generated by CoffeeScript 1.7.1
(function() {
  if (!String.prototype.trim) {
    String.prototype.trim = function() {
      return this.replace(/^\s+|\s+$/g, "");
    };
  }

  String.prototype.strip = function() {
    if (String.prototype.trim != null) {
      return this.trim();
    } else {
      return this.replace(/^\s+|\s+$/g, "");
    }
  };

  String.prototype.lstrip = function() {
    return this.replace(/^\s+/g, "");
  };

  String.prototype.rstrip = function() {
    return this.replace(/\s+$/g, "");
  };

  module.exports.clean_string = function(string) {
    return string.replace(/[\n\t\ ]+/g, ' ').replace('&nbsp;', ' ').replace('&euro;', 'E').strip();
  };

}).call(this);
