// Generated by CoffeeScript 1.7.1
(function() {
  var leboncoin, search;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  leboncoin = require('..');

  search = new leboncoin.Search({
    region: 'haute_normandie',
    query: 'boxe OR box OR stockage OR stocker OR cave OR garage NOT studio NOT F1 NOT F2 NOT F3 NOT T1 NOT T2 NOT T3 NOT appartement',
    category_attrs: {
      mrs: 0,
      mre: 600
    },
    category: 'locations'
  });

  search.perform(function(response) {
    var item, result, _i, _len, _ref;
    if (response.error) {
      console.err(response.error);
      return;
    }
    _ref = response.results;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      result = _ref[_i];
      if (!result.image) {
        continue;
      }
      console.log(result);
      item = new leboncoin.Item(result);
      item.perform(function(result) {
        return console.log(result.attrs);
      });
      return;
    }
  });

}).call(this);
