// Generated by CoffeeScript 1.7.1
(function() {
  var Search, search;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Search = require('..');

  search = new Search({
    region: 'haute_normandie',
    query: 'boxe OR box OR stockage OR stocker OR cave OR garage NOT studio NOT F1 NOT F2 NOT F3 NOT T1 NOT T2 NOT T3 NOT appartement',
    category_attrs: {
      mrs: 0,
      mre: 600
    },
    category: 'locations'
  });

  search.perform(function(response) {
    if (response.error) {
      console.err(response.error);
      return;
    }
    return console.log(response.results);
  });

}).call(this);
