// Generated by CoffeeScript 1.7.1
(function() {
  var Search, search;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Search = require('..');

  search = new Search({
    region: 'haute_normandie',
    location: 27000,
    category_attrs: {
      mrs: 600,
      mre: 1300,
      sqs: 11,
      ret: [1]
    },
    category: 'locations'
  });

  search.perform(function(response) {
    return console.log(response);
  });

}).call(this);
